domain = "ul.lucasvl.nl" # domain to show (cosmetic)
port = 8080 # port that the server runs on
host = "0.0.0.0" # address to listen on, recommended to keep this as is, unless you want to use a unix socket, in which case set it to an empty string
unix_socket = "./socket.sock" # path to the unix socket that you want to use (optional)
title = "File Uploader" # title displayed on browser bar
captcha_site_key = "6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI"
captcha_secret_key = "6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe"
enable_captcha = True
url_length = 7
url_letters = "QWERTYUIOPASDFGHJKLZXCVBNMqwertyuiopasdfghjklzxcvbnm1234567890-_"
max_files = 20
